from __future__ import annotations

import json
from pathlib import Path
from typing import Any


GROUP_FIELD_NAMES = ("id", "groupId")
INTERNAL_FIELD_NAMES = ("internal_id", "internalId", "masterKey", "groupId", "id")


class SignalGroupIdCache:
    def __init__(self, path: Path) -> None:
        self.path = path

    def lookup(self, internal_ids: list[str]) -> str | None:
        mapping = self.load()
        for internal_id in internal_ids:
            group_id = mapping.get(internal_id)
            if _is_sendable_group_id(group_id):
                return group_id
        return None

    def update_from_groups(self, groups: list[dict[str, Any]]) -> dict[str, str]:
        mapping = self.load()
        for group in groups:
            sendable_group_id = _sendable_group_id_from_group(group)
            if not sendable_group_id:
                continue
            mapping[sendable_group_id] = sendable_group_id
            for internal_id in _internal_ids_from_group(group):
                mapping[internal_id] = sendable_group_id
        self.save(mapping)
        return mapping

    def load(self) -> dict[str, str]:
        if not self.path.exists():
            return {}
        mapping: dict[str, str] = {}
        in_groups = False
        for raw_line in self.path.read_text(encoding="utf-8").splitlines():
            line = raw_line.strip()
            if not line or line.startswith("#"):
                continue
            if line == "groups:":
                in_groups = True
                continue
            if not in_groups or ":" not in raw_line:
                continue
            key, value = raw_line.split(":", maxsplit=1)
            key = _parse_yaml_scalar(key.strip())
            value = _parse_yaml_scalar(value.strip())
            if key and _is_sendable_group_id(value):
                mapping[key] = value
        return mapping

    def save(self, mapping: dict[str, str]) -> None:
        self.path.parent.mkdir(parents=True, exist_ok=True)
        lines = [
            "# Generated by ops_bot. Maps Signal receive internal ids to sendable group ids.",
            "groups:",
        ]
        for internal_id, group_id in sorted(mapping.items()):
            lines.append(f"  {_quote_yaml_scalar(internal_id)}: {_quote_yaml_scalar(group_id)}")
        self.path.write_text("\n".join(lines) + "\n", encoding="utf-8")


def _sendable_group_id_from_group(group: dict[str, Any]) -> str | None:
    for field_name in GROUP_FIELD_NAMES:
        value = group.get(field_name)
        if _is_sendable_group_id(value):
            return str(value).strip()
    return None


def _internal_ids_from_group(group: dict[str, Any]) -> list[str]:
    internal_ids: list[str] = []
    for field_name in INTERNAL_FIELD_NAMES:
        value = group.get(field_name)
        if isinstance(value, str) and value.strip():
            internal_ids.append(value.strip())
    return _unique(internal_ids)


def _is_sendable_group_id(group_id: object) -> bool:
    return isinstance(group_id, str) and group_id.strip().startswith("group.")


def _quote_yaml_scalar(value: str) -> str:
    return json.dumps(value, ensure_ascii=False)


def _parse_yaml_scalar(value: str) -> str:
    stripped = value.strip()
    if not stripped:
        return ""
    if stripped[0] in {"'", '"'}:
        try:
            return str(json.loads(stripped))
        except json.JSONDecodeError:
            return stripped.strip("'\"")
    return stripped


def _unique(values: list[str]) -> list[str]:
    seen: set[str] = set()
    unique_values: list[str] = []
    for value in values:
        if value in seen:
            continue
        seen.add(value)
        unique_values.append(value)
    return unique_values
