# ----------------------------------------------------------------------------
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml
#
# ----------------------------------------------------------------------------

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code using: baml-cli generate
# baml-cli is available with the baml package.

import typing
import typing_extensions


from . import stream_types, types
from .runtime import DoNotUseDirectlyCallManager, BamlCallOptions

class LlmResponseParser:
    __options: DoNotUseDirectlyCallManager

    def __init__(self, options: DoNotUseDirectlyCallManager):
        self.__options = options

    def ExtractBalanceRequest(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> types.BalanceExtraction:
        __result__ = self.__options.merge_options(baml_options).parse_response(function_name="ExtractBalanceRequest", llm_response=llm_response, mode="request")
        return typing.cast(types.BalanceExtraction, __result__)

    def ExtractHealthRequest(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> types.HealthExtraction:
        __result__ = self.__options.merge_options(baml_options).parse_response(function_name="ExtractHealthRequest", llm_response=llm_response, mode="request")
        return typing.cast(types.HealthExtraction, __result__)

    def ExtractMonitorRequest(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> types.MonitorExtraction:
        __result__ = self.__options.merge_options(baml_options).parse_response(function_name="ExtractMonitorRequest", llm_response=llm_response, mode="request")
        return typing.cast(types.MonitorExtraction, __result__)

    def ExtractNewListingRequest(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> types.NewListingExtraction:
        __result__ = self.__options.merge_options(baml_options).parse_response(function_name="ExtractNewListingRequest", llm_response=llm_response, mode="request")
        return typing.cast(types.NewListingExtraction, __result__)

    def ExtractStackerStatusRequest(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> types.StackerStatusExtraction:
        __result__ = self.__options.merge_options(baml_options).parse_response(function_name="ExtractStackerStatusRequest", llm_response=llm_response, mode="request")
        return typing.cast(types.StackerStatusExtraction, __result__)

    def ExtractTransferRequest(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> types.TransferExtraction:
        __result__ = self.__options.merge_options(baml_options).parse_response(function_name="ExtractTransferRequest", llm_response=llm_response, mode="request")
        return typing.cast(types.TransferExtraction, __result__)

    def ExtractVolumeFillsRequest(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> types.VolumeFillsExtraction:
        __result__ = self.__options.merge_options(baml_options).parse_response(function_name="ExtractVolumeFillsRequest", llm_response=llm_response, mode="request")
        return typing.cast(types.VolumeFillsExtraction, __result__)

    

class LlmStreamParser:
    __options: DoNotUseDirectlyCallManager

    def __init__(self, options: DoNotUseDirectlyCallManager):
        self.__options = options

    def ExtractBalanceRequest(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> stream_types.BalanceExtraction:
        __result__ = self.__options.merge_options(baml_options).parse_response(function_name="ExtractBalanceRequest", llm_response=llm_response, mode="stream")
        return typing.cast(stream_types.BalanceExtraction, __result__)

    def ExtractHealthRequest(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> stream_types.HealthExtraction:
        __result__ = self.__options.merge_options(baml_options).parse_response(function_name="ExtractHealthRequest", llm_response=llm_response, mode="stream")
        return typing.cast(stream_types.HealthExtraction, __result__)

    def ExtractMonitorRequest(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> stream_types.MonitorExtraction:
        __result__ = self.__options.merge_options(baml_options).parse_response(function_name="ExtractMonitorRequest", llm_response=llm_response, mode="stream")
        return typing.cast(stream_types.MonitorExtraction, __result__)

    def ExtractNewListingRequest(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> stream_types.NewListingExtraction:
        __result__ = self.__options.merge_options(baml_options).parse_response(function_name="ExtractNewListingRequest", llm_response=llm_response, mode="stream")
        return typing.cast(stream_types.NewListingExtraction, __result__)

    def ExtractStackerStatusRequest(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> stream_types.StackerStatusExtraction:
        __result__ = self.__options.merge_options(baml_options).parse_response(function_name="ExtractStackerStatusRequest", llm_response=llm_response, mode="stream")
        return typing.cast(stream_types.StackerStatusExtraction, __result__)

    def ExtractTransferRequest(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> stream_types.TransferExtraction:
        __result__ = self.__options.merge_options(baml_options).parse_response(function_name="ExtractTransferRequest", llm_response=llm_response, mode="stream")
        return typing.cast(stream_types.TransferExtraction, __result__)

    def ExtractVolumeFillsRequest(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> stream_types.VolumeFillsExtraction:
        __result__ = self.__options.merge_options(baml_options).parse_response(function_name="ExtractVolumeFillsRequest", llm_response=llm_response, mode="stream")
        return typing.cast(stream_types.VolumeFillsExtraction, __result__)

    