# ----------------------------------------------------------------------------
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml
#
# ----------------------------------------------------------------------------

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code using: baml-cli generate
# baml-cli is available with the baml package.

import typing
import typing_extensions
from pydantic import BaseModel, ConfigDict, Field

import baml_py

from . import types

StreamStateValueT = typing.TypeVar('StreamStateValueT')
class StreamState(BaseModel, typing.Generic[StreamStateValueT]):
    value: StreamStateValueT
    state: typing_extensions.Literal["Pending", "Incomplete", "Complete"]
# #########################################################################
# Generated classes (7)
# #########################################################################

class BalanceExtraction(BaseModel):
    exchange: typing.Optional[str] = None
    account: typing.Optional[str] = None
    token: typing.Optional[str] = None
    market: typing.Optional[str] = None
    missing_fields: typing.List[str]

class HealthExtraction(BaseModel):
    missing_fields: typing.List[str]

class MonitorExtraction(BaseModel):
    update_time: typing.Optional[int] = None
    missing_fields: typing.List[str]

class NewListingExtraction(BaseModel):
    symbol: typing.Optional[str] = None
    market: typing.Optional[str] = None
    exchanges: typing.Optional[str] = None
    tier: typing.Optional[str] = None
    price_decimals: typing.Optional[int] = None
    quantity_decimals: typing.Optional[int] = None
    feed_port: typing.Optional[int] = None
    gateway_port: typing.Optional[int] = None
    create_new_gate_way: typing.Optional[bool] = None
    missing_fields: typing.List[str]

class StackerStatusExtraction(BaseModel):
    symbol: typing.Optional[str] = None
    date: typing.Optional[str] = None
    missing_fields: typing.List[str]

class TransferExtraction(BaseModel):
    mode: typing.Optional[str] = None
    token: typing.Optional[str] = None
    from_exchange: typing.Optional[str] = None
    amount: typing.Optional[float] = None
    sub_account_name: typing.Optional[str] = None
    to_exchange: typing.Optional[str] = None
    missing_fields: typing.List[str]

class VolumeFillsExtraction(BaseModel):
    symbol: typing.Optional[str] = None
    date: typing.Optional[str] = None
    missing_fields: typing.List[str]

# #########################################################################
# Generated type aliases (0)
# #########################################################################
