# ----------------------------------------------------------------------------
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml
#
# ----------------------------------------------------------------------------

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code using: baml-cli generate
# baml-cli is available with the baml package.

import typing
import typing_extensions
import baml_py

from . import stream_types, types, type_builder
from .parser import LlmResponseParser, LlmStreamParser
from .runtime import DoNotUseDirectlyCallManager, BamlCallOptions
from .globals import DO_NOT_USE_DIRECTLY_UNLESS_YOU_KNOW_WHAT_YOURE_DOING_RUNTIME as __runtime__

class BamlSyncClient:
    __options: DoNotUseDirectlyCallManager
    __stream_client: "BamlStreamClient"
    __http_request: "BamlHttpRequestClient"
    __http_stream_request: "BamlHttpStreamRequestClient"
    __llm_response_parser: LlmResponseParser
    __llm_stream_parser: LlmStreamParser

    def __init__(self, options: DoNotUseDirectlyCallManager):
        self.__options = options
        self.__stream_client = BamlStreamClient(options)
        self.__http_request = BamlHttpRequestClient(options)
        self.__http_stream_request = BamlHttpStreamRequestClient(options)
        self.__llm_response_parser = LlmResponseParser(options)
        self.__llm_stream_parser = LlmStreamParser(options)

    def __getstate__(self):
        # Return state needed for pickling
        return {"options": self.__options}

    def __setstate__(self, state):
        # Restore state from pickling
        self.__options = state["options"]
        self.__stream_client = BamlStreamClient(self.__options)
        self.__http_request = BamlHttpRequestClient(self.__options)
        self.__http_stream_request = BamlHttpStreamRequestClient(self.__options)
        self.__llm_response_parser = LlmResponseParser(self.__options)
        self.__llm_stream_parser = LlmStreamParser(self.__options)

    def with_options(self,
        tb: typing.Optional[type_builder.TypeBuilder] = None,
        client_registry: typing.Optional[baml_py.baml_py.ClientRegistry] = None,
        client: typing.Optional[str] = None,
        collector: typing.Optional[typing.Union[baml_py.baml_py.Collector, typing.List[baml_py.baml_py.Collector]]] = None,
        env: typing.Optional[typing.Dict[str, typing.Optional[str]]] = None,
        tags: typing.Optional[typing.Dict[str, str]] = None,
        on_tick: typing.Optional[typing.Callable[[str, baml_py.baml_py.FunctionLog], None]] = None,
    ) -> "BamlSyncClient":
        options: BamlCallOptions = {}
        if tb is not None:
            options["tb"] = tb
        if client_registry is not None:
            options["client_registry"] = client_registry
        if client is not None:
            options["client"] = client
        if collector is not None:
            options["collector"] = collector
        if env is not None:
            options["env"] = env
        if tags is not None:
            options["tags"] = tags
        if on_tick is not None:
            options["on_tick"] = on_tick
        return BamlSyncClient(self.__options.merge_options(options))

    @property
    def stream(self):
      return self.__stream_client

    @property
    def request(self):
      return self.__http_request

    @property
    def stream_request(self):
      return self.__http_stream_request

    @property
    def parse(self):
      return self.__llm_response_parser

    @property
    def parse_stream(self):
      return self.__llm_stream_parser

    def ExtractBalanceRequest(self, user_question: str,
        baml_options: BamlCallOptions = {},
    ) -> types.BalanceExtraction:
        # Check if on_tick is provided
        if 'on_tick' in baml_options:
            __stream__ = self.stream.ExtractBalanceRequest(user_question=user_question,
                baml_options=baml_options)
            return __stream__.get_final_response()
        else:
            # Original non-streaming code
            __result__ = self.__options.merge_options(baml_options).call_function_sync(function_name="ExtractBalanceRequest", args={
                "user_question": user_question,
            })
            return typing.cast(types.BalanceExtraction, __result__.cast_to(types, types, stream_types, False, __runtime__))
    def ExtractHealthRequest(self, user_question: str,
        baml_options: BamlCallOptions = {},
    ) -> types.HealthExtraction:
        # Check if on_tick is provided
        if 'on_tick' in baml_options:
            __stream__ = self.stream.ExtractHealthRequest(user_question=user_question,
                baml_options=baml_options)
            return __stream__.get_final_response()
        else:
            # Original non-streaming code
            __result__ = self.__options.merge_options(baml_options).call_function_sync(function_name="ExtractHealthRequest", args={
                "user_question": user_question,
            })
            return typing.cast(types.HealthExtraction, __result__.cast_to(types, types, stream_types, False, __runtime__))
    def ExtractMonitorRequest(self, user_question: str,
        baml_options: BamlCallOptions = {},
    ) -> types.MonitorExtraction:
        # Check if on_tick is provided
        if 'on_tick' in baml_options:
            __stream__ = self.stream.ExtractMonitorRequest(user_question=user_question,
                baml_options=baml_options)
            return __stream__.get_final_response()
        else:
            # Original non-streaming code
            __result__ = self.__options.merge_options(baml_options).call_function_sync(function_name="ExtractMonitorRequest", args={
                "user_question": user_question,
            })
            return typing.cast(types.MonitorExtraction, __result__.cast_to(types, types, stream_types, False, __runtime__))
    def ExtractNewListingRequest(self, user_question: str,
        baml_options: BamlCallOptions = {},
    ) -> types.NewListingExtraction:
        # Check if on_tick is provided
        if 'on_tick' in baml_options:
            __stream__ = self.stream.ExtractNewListingRequest(user_question=user_question,
                baml_options=baml_options)
            return __stream__.get_final_response()
        else:
            # Original non-streaming code
            __result__ = self.__options.merge_options(baml_options).call_function_sync(function_name="ExtractNewListingRequest", args={
                "user_question": user_question,
            })
            return typing.cast(types.NewListingExtraction, __result__.cast_to(types, types, stream_types, False, __runtime__))
    def ExtractStackerStatusRequest(self, user_question: str,
        baml_options: BamlCallOptions = {},
    ) -> types.StackerStatusExtraction:
        # Check if on_tick is provided
        if 'on_tick' in baml_options:
            __stream__ = self.stream.ExtractStackerStatusRequest(user_question=user_question,
                baml_options=baml_options)
            return __stream__.get_final_response()
        else:
            # Original non-streaming code
            __result__ = self.__options.merge_options(baml_options).call_function_sync(function_name="ExtractStackerStatusRequest", args={
                "user_question": user_question,
            })
            return typing.cast(types.StackerStatusExtraction, __result__.cast_to(types, types, stream_types, False, __runtime__))
    def ExtractTransferRequest(self, user_question: str,
        baml_options: BamlCallOptions = {},
    ) -> types.TransferExtraction:
        # Check if on_tick is provided
        if 'on_tick' in baml_options:
            __stream__ = self.stream.ExtractTransferRequest(user_question=user_question,
                baml_options=baml_options)
            return __stream__.get_final_response()
        else:
            # Original non-streaming code
            __result__ = self.__options.merge_options(baml_options).call_function_sync(function_name="ExtractTransferRequest", args={
                "user_question": user_question,
            })
            return typing.cast(types.TransferExtraction, __result__.cast_to(types, types, stream_types, False, __runtime__))
    def ExtractVolumeFillsRequest(self, user_question: str,
        baml_options: BamlCallOptions = {},
    ) -> types.VolumeFillsExtraction:
        # Check if on_tick is provided
        if 'on_tick' in baml_options:
            __stream__ = self.stream.ExtractVolumeFillsRequest(user_question=user_question,
                baml_options=baml_options)
            return __stream__.get_final_response()
        else:
            # Original non-streaming code
            __result__ = self.__options.merge_options(baml_options).call_function_sync(function_name="ExtractVolumeFillsRequest", args={
                "user_question": user_question,
            })
            return typing.cast(types.VolumeFillsExtraction, __result__.cast_to(types, types, stream_types, False, __runtime__))
    


class BamlStreamClient:
    __options: DoNotUseDirectlyCallManager

    def __init__(self, options: DoNotUseDirectlyCallManager):
        self.__options = options

    def ExtractBalanceRequest(self, user_question: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.BamlSyncStream[stream_types.BalanceExtraction, types.BalanceExtraction]:
        __ctx__, __result__ = self.__options.merge_options(baml_options).create_sync_stream(function_name="ExtractBalanceRequest", args={
            "user_question": user_question,
        })
        return baml_py.BamlSyncStream[stream_types.BalanceExtraction, types.BalanceExtraction](
          __result__,
          lambda x: typing.cast(stream_types.BalanceExtraction, x.cast_to(types, types, stream_types, True, __runtime__)),
          lambda x: typing.cast(types.BalanceExtraction, x.cast_to(types, types, stream_types, False, __runtime__)),
          __ctx__,
        )
    def ExtractHealthRequest(self, user_question: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.BamlSyncStream[stream_types.HealthExtraction, types.HealthExtraction]:
        __ctx__, __result__ = self.__options.merge_options(baml_options).create_sync_stream(function_name="ExtractHealthRequest", args={
            "user_question": user_question,
        })
        return baml_py.BamlSyncStream[stream_types.HealthExtraction, types.HealthExtraction](
          __result__,
          lambda x: typing.cast(stream_types.HealthExtraction, x.cast_to(types, types, stream_types, True, __runtime__)),
          lambda x: typing.cast(types.HealthExtraction, x.cast_to(types, types, stream_types, False, __runtime__)),
          __ctx__,
        )
    def ExtractMonitorRequest(self, user_question: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.BamlSyncStream[stream_types.MonitorExtraction, types.MonitorExtraction]:
        __ctx__, __result__ = self.__options.merge_options(baml_options).create_sync_stream(function_name="ExtractMonitorRequest", args={
            "user_question": user_question,
        })
        return baml_py.BamlSyncStream[stream_types.MonitorExtraction, types.MonitorExtraction](
          __result__,
          lambda x: typing.cast(stream_types.MonitorExtraction, x.cast_to(types, types, stream_types, True, __runtime__)),
          lambda x: typing.cast(types.MonitorExtraction, x.cast_to(types, types, stream_types, False, __runtime__)),
          __ctx__,
        )
    def ExtractNewListingRequest(self, user_question: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.BamlSyncStream[stream_types.NewListingExtraction, types.NewListingExtraction]:
        __ctx__, __result__ = self.__options.merge_options(baml_options).create_sync_stream(function_name="ExtractNewListingRequest", args={
            "user_question": user_question,
        })
        return baml_py.BamlSyncStream[stream_types.NewListingExtraction, types.NewListingExtraction](
          __result__,
          lambda x: typing.cast(stream_types.NewListingExtraction, x.cast_to(types, types, stream_types, True, __runtime__)),
          lambda x: typing.cast(types.NewListingExtraction, x.cast_to(types, types, stream_types, False, __runtime__)),
          __ctx__,
        )
    def ExtractStackerStatusRequest(self, user_question: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.BamlSyncStream[stream_types.StackerStatusExtraction, types.StackerStatusExtraction]:
        __ctx__, __result__ = self.__options.merge_options(baml_options).create_sync_stream(function_name="ExtractStackerStatusRequest", args={
            "user_question": user_question,
        })
        return baml_py.BamlSyncStream[stream_types.StackerStatusExtraction, types.StackerStatusExtraction](
          __result__,
          lambda x: typing.cast(stream_types.StackerStatusExtraction, x.cast_to(types, types, stream_types, True, __runtime__)),
          lambda x: typing.cast(types.StackerStatusExtraction, x.cast_to(types, types, stream_types, False, __runtime__)),
          __ctx__,
        )
    def ExtractTransferRequest(self, user_question: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.BamlSyncStream[stream_types.TransferExtraction, types.TransferExtraction]:
        __ctx__, __result__ = self.__options.merge_options(baml_options).create_sync_stream(function_name="ExtractTransferRequest", args={
            "user_question": user_question,
        })
        return baml_py.BamlSyncStream[stream_types.TransferExtraction, types.TransferExtraction](
          __result__,
          lambda x: typing.cast(stream_types.TransferExtraction, x.cast_to(types, types, stream_types, True, __runtime__)),
          lambda x: typing.cast(types.TransferExtraction, x.cast_to(types, types, stream_types, False, __runtime__)),
          __ctx__,
        )
    def ExtractVolumeFillsRequest(self, user_question: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.BamlSyncStream[stream_types.VolumeFillsExtraction, types.VolumeFillsExtraction]:
        __ctx__, __result__ = self.__options.merge_options(baml_options).create_sync_stream(function_name="ExtractVolumeFillsRequest", args={
            "user_question": user_question,
        })
        return baml_py.BamlSyncStream[stream_types.VolumeFillsExtraction, types.VolumeFillsExtraction](
          __result__,
          lambda x: typing.cast(stream_types.VolumeFillsExtraction, x.cast_to(types, types, stream_types, True, __runtime__)),
          lambda x: typing.cast(types.VolumeFillsExtraction, x.cast_to(types, types, stream_types, False, __runtime__)),
          __ctx__,
        )
    

class BamlHttpRequestClient:
    __options: DoNotUseDirectlyCallManager

    def __init__(self, options: DoNotUseDirectlyCallManager):
        self.__options = options

    def ExtractBalanceRequest(self, user_question: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        __result__ = self.__options.merge_options(baml_options).create_http_request_sync(function_name="ExtractBalanceRequest", args={
            "user_question": user_question,
        }, mode="request")
        return __result__
    def ExtractHealthRequest(self, user_question: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        __result__ = self.__options.merge_options(baml_options).create_http_request_sync(function_name="ExtractHealthRequest", args={
            "user_question": user_question,
        }, mode="request")
        return __result__
    def ExtractMonitorRequest(self, user_question: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        __result__ = self.__options.merge_options(baml_options).create_http_request_sync(function_name="ExtractMonitorRequest", args={
            "user_question": user_question,
        }, mode="request")
        return __result__
    def ExtractNewListingRequest(self, user_question: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        __result__ = self.__options.merge_options(baml_options).create_http_request_sync(function_name="ExtractNewListingRequest", args={
            "user_question": user_question,
        }, mode="request")
        return __result__
    def ExtractStackerStatusRequest(self, user_question: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        __result__ = self.__options.merge_options(baml_options).create_http_request_sync(function_name="ExtractStackerStatusRequest", args={
            "user_question": user_question,
        }, mode="request")
        return __result__
    def ExtractTransferRequest(self, user_question: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        __result__ = self.__options.merge_options(baml_options).create_http_request_sync(function_name="ExtractTransferRequest", args={
            "user_question": user_question,
        }, mode="request")
        return __result__
    def ExtractVolumeFillsRequest(self, user_question: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        __result__ = self.__options.merge_options(baml_options).create_http_request_sync(function_name="ExtractVolumeFillsRequest", args={
            "user_question": user_question,
        }, mode="request")
        return __result__
    

class BamlHttpStreamRequestClient:
    __options: DoNotUseDirectlyCallManager

    def __init__(self, options: DoNotUseDirectlyCallManager):
        self.__options = options

    def ExtractBalanceRequest(self, user_question: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        __result__ = self.__options.merge_options(baml_options).create_http_request_sync(function_name="ExtractBalanceRequest", args={
            "user_question": user_question,
        }, mode="stream")
        return __result__
    def ExtractHealthRequest(self, user_question: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        __result__ = self.__options.merge_options(baml_options).create_http_request_sync(function_name="ExtractHealthRequest", args={
            "user_question": user_question,
        }, mode="stream")
        return __result__
    def ExtractMonitorRequest(self, user_question: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        __result__ = self.__options.merge_options(baml_options).create_http_request_sync(function_name="ExtractMonitorRequest", args={
            "user_question": user_question,
        }, mode="stream")
        return __result__
    def ExtractNewListingRequest(self, user_question: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        __result__ = self.__options.merge_options(baml_options).create_http_request_sync(function_name="ExtractNewListingRequest", args={
            "user_question": user_question,
        }, mode="stream")
        return __result__
    def ExtractStackerStatusRequest(self, user_question: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        __result__ = self.__options.merge_options(baml_options).create_http_request_sync(function_name="ExtractStackerStatusRequest", args={
            "user_question": user_question,
        }, mode="stream")
        return __result__
    def ExtractTransferRequest(self, user_question: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        __result__ = self.__options.merge_options(baml_options).create_http_request_sync(function_name="ExtractTransferRequest", args={
            "user_question": user_question,
        }, mode="stream")
        return __result__
    def ExtractVolumeFillsRequest(self, user_question: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        __result__ = self.__options.merge_options(baml_options).create_http_request_sync(function_name="ExtractVolumeFillsRequest", args={
            "user_question": user_question,
        }, mode="stream")
        return __result__
    

b = BamlSyncClient(DoNotUseDirectlyCallManager({}))