# ----------------------------------------------------------------------------
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml
#
# ----------------------------------------------------------------------------

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code using: baml-cli generate
# baml-cli is available with the baml package.

from . import types
from . import stream_types


type_map = {

    "types.BalanceExtraction": types.BalanceExtraction,
    "stream_types.BalanceExtraction": stream_types.BalanceExtraction,

    "types.HealthExtraction": types.HealthExtraction,
    "stream_types.HealthExtraction": stream_types.HealthExtraction,

    "types.MonitorExtraction": types.MonitorExtraction,
    "stream_types.MonitorExtraction": stream_types.MonitorExtraction,

    "types.StackerStatusExtraction": types.StackerStatusExtraction,
    "stream_types.StackerStatusExtraction": stream_types.StackerStatusExtraction,

    "types.TransferExtraction": types.TransferExtraction,
    "stream_types.TransferExtraction": stream_types.TransferExtraction,

    "types.VolumeFillsExtraction": types.VolumeFillsExtraction,
    "stream_types.VolumeFillsExtraction": stream_types.VolumeFillsExtraction,


}