# ----------------------------------------------------------------------------
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml
#
# ----------------------------------------------------------------------------

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code using: baml-cli generate
# baml-cli is available with the baml package.

import typing
import typing_extensions
from enum import Enum


from pydantic import BaseModel, ConfigDict, Field


import baml_py

CheckT = typing_extensions.TypeVar('CheckT')
CheckName = typing_extensions.TypeVar('CheckName', bound=str)

class Check(BaseModel):
    name: str
    expression: str
    status: str
class Checked(BaseModel, typing.Generic[CheckT, CheckName]):
    value: CheckT
    checks: typing.Dict[CheckName, Check]

def get_checks(checks: typing.Dict[CheckName, Check]) -> typing.List[Check]:
    return list(checks.values())

def all_succeeded(checks: typing.Dict[CheckName, Check]) -> bool:
    return all(check.status == "succeeded" for check in get_checks(checks))
# #########################################################################
# Generated enums (0)
# #########################################################################

# #########################################################################
# Generated classes (7)
# #########################################################################

class BalanceExtraction(BaseModel):
    exchange: typing.Optional[str] = None
    account: typing.Optional[str] = None
    token: typing.Optional[str] = None
    market: typing.Optional[str] = None
    missing_fields: typing.List[str]

class HealthExtraction(BaseModel):
    missing_fields: typing.List[str]

class MonitorExtraction(BaseModel):
    update_time: typing.Optional[int] = None
    missing_fields: typing.List[str]

class NewListingExtraction(BaseModel):
    symbol: typing.Optional[str] = None
    quote_currency: typing.Optional[str] = None
    box_name: typing.Optional[str] = None
    market: typing.Optional[str] = None
    exchanges: typing.Optional[str] = None
    tier: typing.Optional[str] = None
    price_decimals: typing.Optional[int] = None
    quantity_decimals: typing.Optional[int] = None
    feed_port: typing.Optional[int] = None
    gateway_port: typing.Optional[int] = None
    create_new_gate_way: typing.Optional[bool] = None
    missing_fields: typing.List[str]

class StackerStatusExtraction(BaseModel):
    symbol: typing.Optional[str] = None
    date: typing.Optional[str] = None
    missing_fields: typing.List[str]

class TransferExtraction(BaseModel):
    mode: typing.Optional[str] = None
    token: typing.Optional[str] = None
    from_exchange: typing.Optional[str] = None
    amount: typing.Optional[float] = None
    sub_account_name: typing.Optional[str] = None
    to_exchange: typing.Optional[str] = None
    missing_fields: typing.List[str]

class VolumeFillsExtraction(BaseModel):
    symbol: typing.Optional[str] = None
    date: typing.Optional[str] = None
    missing_fields: typing.List[str]

# #########################################################################
# Generated type aliases (0)
# #########################################################################
